"""Shared helpers for observable-behavior tests."""

from __future__ import annotations

import json
from pathlib import Path

from simula.infrastructure.config.models import (
    AppSettings,
    ModelConfig,
    ModelRouterConfig,
    StorageConfig,
)


def sample_analysis_log_text(*, run_id: str) -> str:
    entries = [
        {
            "index": 1,
            "event": "simulation_started",
            "event_key": "simulation_started",
            "run_id": run_id,
            "scenario": "scenario",
            "max_rounds": 2,
            "rng_seed": 1234,
        },
        {
            "index": 2,
            "event": "actors_finalized",
            "event_key": "actors_finalized",
            "run_id": run_id,
            "actors": [
                {"cast_id": "alpha", "display_name": "Alpha"},
                {"cast_id": "beta", "display_name": "Beta"},
                {"cast_id": "gamma", "display_name": "Gamma"},
            ],
        },
        {
            "index": 3,
            "event": "plan_finalized",
            "event_key": "plan_finalized",
            "run_id": run_id,
            "plan": {
                "progression_plan": {"max_rounds": 3},
                "action_catalog": {
                    "actions": [
                        {
                            "action_type": "private_check_in",
                            "label": "비공개 확인",
                            "description": "상대의 반응을 제한 채널에서 확인한다.",
                            "supported_visibility": ["private"],
                            "requires_target": True,
                            "supports_utterance": True,
                        },
                        {
                            "action_type": "public_signal",
                            "label": "공개 신호",
                            "description": "직접 지목하지 않고 공개적으로 신호를 보낸다.",
                            "supported_visibility": ["public"],
                            "requires_target": False,
                            "supports_utterance": True,
                        },
                        {
                            "action_type": "unused_action",
                            "label": "미채택 행동",
                            "description": "후보에는 있었지만 채택되지 않는다.",
                            "supported_visibility": ["group"],
                            "requires_target": True,
                            "supports_utterance": False,
                        },
                    ]
                },
            },
        },
        {
            "index": 4,
            "event": "llm_call",
            "event_key": "llm_call:1",
            "run_id": run_id,
            "sequence": 1,
            "role": "planner",
            "call_kind": "structured",
            "log_context": {
                "scope": "planning-analysis",
                "phase": "planning",
                "task_key": "planning_analysis",
                "task_label": "계획 분석",
                "artifact_key": "planning_analysis",
                "artifact_label": "planning_analysis",
                "schema_name": "PlanningAnalysis",
            },
            "prompt": "planner prompt",
            "raw_response": "{\"brief_summary\":\"ok\"}",
            "duration_seconds": 0.3,
            "ttft_seconds": 0.1,
            "input_tokens": 10,
            "output_tokens": None,
            "total_tokens": 10,
        },
        {
            "index": 5,
            "event": "llm_call",
            "event_key": "llm_call:2",
            "run_id": run_id,
            "sequence": 2,
            "role": "actor",
            "call_kind": "structured",
            "log_context": {
                "scope": "actor-turn",
                "phase": "runtime",
                "task_key": "actor_action_proposal",
                "task_label": "행동 제안",
                "artifact_key": "pending_actor_proposals",
                "artifact_label": "pending_actor_proposals",
                "schema_name": "ActorActionProposal",
                "cast_id": "alpha",
            },
            "prompt": "actor prompt",
            "raw_response": "{\"action_type\":\"talk\"}",
            "duration_seconds": 0.4,
            "ttft_seconds": 0.2,
            "input_tokens": 10,
            "output_tokens": 5,
            "total_tokens": 15,
        },
        {
            "index": 6,
            "event": "llm_call",
            "event_key": "llm_call:3",
            "run_id": run_id,
            "sequence": 3,
            "role": "fixer",
            "call_kind": "text",
            "log_context": {
                "scope": "json-fix",
                "phase": "repair",
                "task_key": "json_repair.actor.actor_action_proposal",
                "task_label": "JSON 복구 (actor · 행동 제안)",
                "artifact_key": "repaired_json",
                "artifact_label": "repaired_json",
                "target_role": "actor",
                "target_task_key": "actor_action_proposal",
                "target_artifact_key": "pending_actor_proposals",
                "target_schema_name": "ActorActionProposal",
                "attempt": 1,
            },
            "prompt": "Target schema: ActorActionProposal\nFields:\n- x",
            "raw_response": "{\"fixed\":1}",
            "duration_seconds": 0.25,
            "ttft_seconds": 0.08,
            "input_tokens": 10,
            "output_tokens": 3,
            "total_tokens": 13,
        },
        {
            "index": 7,
            "event": "llm_call",
            "event_key": "llm_call:4",
            "run_id": run_id,
            "sequence": 4,
            "role": "fixer",
            "call_kind": "text",
            "log_context": {
                "scope": "json-fix",
                "phase": "repair",
                "task_key": "json_repair.actor.actor_action_proposal",
                "task_label": "JSON 복구 (actor · 행동 제안)",
                "artifact_key": "repaired_json",
                "artifact_label": "repaired_json",
                "target_role": "actor",
                "target_task_key": "actor_action_proposal",
                "target_artifact_key": "pending_actor_proposals",
                "target_schema_name": "ActorActionProposal",
                "attempt": 2,
            },
            "prompt": "Target schema: ActorActionProposal\nFields:\n- x",
            "raw_response": "{\"fixed\":2}",
            "duration_seconds": 0.35,
            "ttft_seconds": 0.09,
            "input_tokens": 10,
            "output_tokens": 4,
            "total_tokens": 14,
        },
        {
            "index": 8,
            "event": "llm_call",
            "event_key": "llm_call:5",
            "run_id": run_id,
            "sequence": 5,
            "role": "fixer",
            "call_kind": "text",
            "log_context": {
                "scope": "json-fix",
                "phase": "repair",
                "task_key": "json_repair.observer.timeline_anchor",
                "task_label": "JSON 복구 (observer · 타임라인 anchor 결정)",
                "artifact_key": "repaired_json",
                "artifact_label": "repaired_json",
                "target_role": "observer",
                "target_task_key": "timeline_anchor",
                "target_artifact_key": "report_timeline_anchor_json",
                "target_schema_name": "TimelineAnchorDecision",
                "attempt": 1,
            },
            "prompt": "Target schema: TimelineAnchorDecision\nFields:\n- x",
            "raw_response": "{\"fixed\":3}",
            "duration_seconds": 0.45,
            "ttft_seconds": 0.11,
            "input_tokens": 10,
            "output_tokens": 6,
            "total_tokens": 16,
        },
        {
            "index": 9,
            "event": "round_actions_adopted",
            "event_key": "round_actions_adopted:1",
            "run_id": run_id,
            "round_index": 1,
            "activities": [
                {
                    "round_index": 1,
                    "source_cast_id": "alpha",
                    "target_cast_ids": ["beta"],
                    "intent_target_cast_ids": ["beta", "gamma"],
                    "action_type": "private_check_in",
                    "intent": "Beta의 반응을 비공개로 확인한다.",
                    "action_summary": "Alpha가 Beta에게 비공개로 확인을 요청한다.",
                    "action_detail": "지금 감정선을 비공개로 먼저 확인하려고 한다.",
                    "utterance": "지금 잠깐 따로 이야기할래?",
                    "visibility": "private",
                    "thread_id": "pair-thread",
                },
                {
                    "round_index": 1,
                    "source_cast_id": "beta",
                    "target_cast_ids": [],
                    "intent_target_cast_ids": ["alpha"],
                    "action_type": "public_signal",
                    "intent": "Alpha를 공개적으로 의식한다.",
                    "action_summary": "Beta가 Alpha를 공개적으로 의식한다.",
                    "action_detail": "직접 지목하진 않지만 시선을 보내며 반응을 탐색한다.",
                    "utterance": "오늘 분위기가 좀 다르네요.",
                    "visibility": "public",
                    "thread_id": "",
                },
            ],
        },
    ]
    return "".join(json.dumps(item, ensure_ascii=False) + "\n" for item in entries)


def build_analysis_settings(*, output_dir: Path) -> AppSettings:
    model = ModelConfig(provider="ollama", model="dummy")
    return AppSettings(
        storage=StorageConfig(
            output_dir=str(output_dir),
            sqlite_path=str(output_dir / "runtime.sqlite"),
        ),
        models=ModelRouterConfig(
            planner=model,
            generator=model,
            coordinator=model,
            actor=model,
            observer=model,
            fixer=model,
        ),
    )
