/**
 * Purpose: Verify actor history presentation, scrolling, and retained report replay access.
 * Pattern: Browser workflow test.
 * Usage: bun run test:e2e apps/web/e2e/actor-rail.e2e.ts
 * Related: src/ui/components/actors, src/ui/pages/report-page.tsx
 */
import { expect, test } from "./fixtures"

test("groups actor history by round with thoughts and speech in one card", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.addInitScript(() => localStorage.setItem("simula.language", "en"))
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  expect((await page.request.put("/api/settings", { data: { settings } })).ok()).toBe(true)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto("/")
  const chooser = page.waitForEvent("filechooser")
  await page.getByRole("button", { name: /Import finished scenario/ }).click()
  await (await chooser).setFiles({ name: "actor-history.md", mimeType: "text/markdown", buffer: Buffer.from("A product team debates a risky release.") })
  await page.getByLabel("Cast size").fill("3")
  await page.getByLabel("Max round").fill("2")
  await page.getByRole("switch", { name: "Auto continue" }).check()
  await page.getByRole("button", { name: "Start", exact: true }).click()
  await expect(page.getByRole("dialog", { name: "Move to the Report page?" })).toBeVisible({ timeout: 25000 })
  await page.getByRole("button", { name: "Keep watching" }).click()
  const rail = page.getByRole("complementary", { name: "Actor history" })
  await expect(rail.getByRole("heading", { name: "ROUND 1", exact: true })).toHaveCount(1)
  await expect(rail.getByRole("heading", { name: "ROUND 2", exact: true })).toHaveCount(1)
  const card = rail.getByRole("article").first()
  await expect(card.getByLabel("Thought", { exact: true })).not.toBeEmpty()
  await expect(card.getByLabel("Action", { exact: true })).not.toBeEmpty()
  await expect(card.getByLabel("Speech", { exact: true })).not.toBeEmpty()
  const thoughtColor = await card.getByLabel("Thought", { exact: true }).evaluate(element => getComputedStyle(element).color)
  const speechColor = await card.getByLabel("Speech", { exact: true }).evaluate(element => getComputedStyle(element).color)
  expect(thoughtColor).not.toBe(speechColor)
  expect(speechColor).toBe("rgb(0, 0, 0)")
  const ratio = await rail.evaluate(element => {
    const graph = element.previousElementSibling!.getBoundingClientRect()
    return graph.width / (graph.width + element.getBoundingClientRect().width)
  })
  expect(ratio).toBeCloseTo(0.6, 2)
  await page.setViewportSize({ width: 2393, height: 1267 })
  await expect(page.getByRole("heading", { name: "Simulation", exact: true })).toBeVisible()
  await expect.poll(() => rail.evaluate(element => {
    const stage = element.previousElementSibling!.getBoundingClientRect()
    const history = element.getBoundingClientRect()
    return Math.abs(stage.top - history.top)
  })).toBeLessThanOrEqual(1)
  const margins = await rail.evaluate(element => ({
    left: element.previousElementSibling!.getBoundingClientRect().left / innerWidth,
    right: (innerWidth - element.getBoundingClientRect().right) / innerWidth,
  }))
  expect(margins.left).toBeCloseTo(0.1, 2)
  expect(margins.right).toBeCloseTo(0.1, 2)
  await page.screenshot({ path: testInfo.outputPath("simulation-wide.png"), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1100 })
  await expect(rail.locator('[data-slot="scroll-area-viewport"]')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight)).toBe(true)
  await page.evaluate(() => window.scrollTo(0, 0))
  await expect(page.getByText("Simulation started", { exact: true })).toBeHidden({ timeout: 6000 })
  await page.screenshot({ path: testInfo.outputPath("actor-rail-desktop.png"), fullPage: true })
  await expect(page.getByRole("button", { name: "Reset replay" })).toHaveCount(0)
  await expect(page.getByRole("slider", { name: "Replay timeline" })).toHaveCount(0)
  const actorName = card.getByRole("button", { name: /^View / })
  expect(await actorName.evaluate(element => getComputedStyle(element).borderWidth)).toBe("0px")
  const actorLabel = await actorName.innerText()
  await actorName.click()
  await expect(page.getByRole("dialog", { name: actorLabel, exact: true })).toBeVisible()
  await page.keyboard.press("Escape")
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.getByRole("button", { name: "Report", exact: true }).click()
  await page.getByRole("button", { name: "Relationships" }).click()
  await expect(page.getByRole("slider", { name: "Replay timeline" }).first()).toBeVisible()
  expect(errors).toEqual([])
})

test("pauses following when scrolled up and resumes only at the bottom", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.addInitScript(() => localStorage.setItem("simula.language", "en"))
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  await page.request.put("/api/settings", { data: { settings } })
  const continuations: import("@playwright/test").Route[] = []
  await page.route("**/api/runs/*/continue", route => { continuations.push(route) })
  await page.goto("/")
  const chooser = page.waitForEvent("filechooser")
  await page.getByRole("button", { name: /Import finished scenario/ }).click()
  await (await chooser).setFiles({ name: "scroll-history.md", mimeType: "text/markdown", buffer: Buffer.from("A product team debates a risky release.") })
  await page.getByLabel("Cast size").fill("6")
  await page.getByLabel("Max round").fill("3")
  await page.getByRole("switch", { name: "Auto continue" }).check()
  await page.getByRole("button", { name: "Start", exact: true }).click()
  const rail = page.getByRole("complementary", { name: "Actor history" })
  const bottomGap = () => page.evaluate(() => document.documentElement.scrollHeight - scrollY - innerHeight)
  await expect.poll(() => continuations.length, { timeout: 12000 }).toBe(1)
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
  const bottom = await page.evaluate(() => scrollY)
  expect(bottom).toBeGreaterThan(48)
  await rail.hover()
  await page.mouse.wheel(0, -24)
  await expect.poll(bottomGap).toBeGreaterThan(1)
  const readingPosition = await page.evaluate(() => scrollY)
  expect(bottom - readingPosition).toBeLessThan(64)
  await continuations[0].continue()
  await expect.poll(() => continuations.length, { timeout: 12000 }).toBe(2)
  await expect(rail.getByRole("heading", { name: "ROUND 2", exact: true })).toHaveCount(1)
  await expect.poll(bottomGap).toBeGreaterThan(1)
  expect(await page.evaluate(() => scrollY)).toBeLessThanOrEqual(readingPosition)
  await page.mouse.wheel(0, 10000)
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
  await continuations[1].continue()
  await expect(page.getByRole("dialog", { name: "Move to the Report page?" })).toBeVisible({ timeout: 20000 })
  await page.getByRole("button", { name: "Keep watching" }).click()
  await expect(rail.getByRole("heading", { name: "ROUND 3", exact: true })).toHaveCount(1)
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
})

test("Planner action codes resolve to Korean badges to the left of speech", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("simula.language", "ko"))
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  await page.request.put("/api/settings", { data: { settings } })
  await page.goto("/")
  const chooser = page.waitForEvent("filechooser")
  await page.getByRole("button", { name: /완성된 시나리오 불러오기/ }).click()
  await (await chooser).setFiles({ name: "action-catalog.md", mimeType: "text/markdown", buffer: Buffer.from("민수와 지수가 안전한 출시를 논의합니다.") })
  await page.getByLabel("등장 인원").fill("3")
  await page.getByLabel("최대 라운드").fill("1")
  await page.getByRole("button", { name: "시작하기", exact: true }).click()
  await page.getByRole("button", { name: "계속 보기", exact: true }).click()
  const card = page.getByRole("complementary").getByRole("article").first()
  const badge = card.locator('[data-slot="badge"]')
  await expect(badge).toHaveText("근거 요청")
  const positions = await card.evaluate((element) => {
    const badge = element.querySelector('[data-slot="badge"]')!.getBoundingClientRect()
    const speech = element.querySelector('[aria-label="발화"]')!.getBoundingClientRect()
    return { badgeRight: badge.right, speechLeft: speech.left }
  })
  expect(positions.badgeRight).toBeLessThanOrEqual(positions.speechLeft)
  await expect(card).not.toContainText("Public move")
  const { runId } = await page.evaluate(() => JSON.parse(sessionStorage.getItem("simula.run-session")!))
  const detail = await (await page.request.get(`/api/runs/${runId}`)).json()
  expect(Object.keys(detail.state.plan.actionCatalog)).toHaveLength(12)
  const interaction = detail.state.interactions.find((item: { decisionType: string }) => item.decisionType === "action")
  expect(detail.state.plan.actionCatalog[interaction.actionCode].label).toBe(interaction.actionType)
})
