import { expect, test } from "@playwright/test"

test("groups actor history by round with thoughts and speech in one card", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.addInitScript(() => localStorage.setItem("simula.language", "en"))
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  expect((await page.request.put("/api/settings", { data: { settings } })).ok()).toBe(true)
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.goto("/")
  const chooser = page.waitForEvent("filechooser")
  await page.getByRole("button", { name: /Upload My Scenario/ }).click()
  await (await chooser).setFiles({ name: "actor-history.md", mimeType: "text/markdown", buffer: Buffer.from("A product team debates a risky release.") })
  await page.getByLabel("Cast size").fill("3")
  await page.getByLabel("Max round").fill("2")
  await page.getByRole("switch", { name: "Auto continue" }).check()
  await page.getByRole("button", { name: "Start", exact: true }).click()
  await expect(page.getByRole("dialog", { name: "Move to the Report page?" })).toBeVisible({ timeout: 25000 })
  await page.getByRole("button", { name: "Keep watching" }).click()
  const rail = page.getByRole("complementary", { name: "Actor history" })
  await expect(rail.getByRole("heading", { name: "ROUND 1", exact: true })).toHaveCount(1)
  await expect(rail.getByRole("heading", { name: "ROUND 2", exact: true })).toHaveCount(1)
  const card = rail.getByRole("article").first()
  await expect(card.getByLabel("Thought", { exact: true })).not.toBeEmpty()
  await expect(card.getByLabel("Action", { exact: true })).not.toBeEmpty()
  await expect(card.getByLabel("Speech", { exact: true })).not.toBeEmpty()
  const thoughtColor = await card.getByLabel("Thought", { exact: true }).evaluate(element => getComputedStyle(element).color)
  const speechColor = await card.getByLabel("Speech", { exact: true }).evaluate(element => getComputedStyle(element).color)
  expect(thoughtColor).not.toBe(speechColor)
  expect(speechColor).toBe("rgb(0, 0, 0)")
  const ratio = await rail.evaluate(element => {
    const graph = element.previousElementSibling!.getBoundingClientRect()
    return graph.width / (graph.width + element.getBoundingClientRect().width)
  })
  expect(ratio).toBeCloseTo(0.6, 2)
  const viewport = rail.locator('[data-slot="scroll-area-viewport"]')
  expect(await viewport.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
  await viewport.evaluate(element => { element.scrollTop = 0 })
  await expect(page.getByText("Simulation started", { exact: true })).toBeHidden({ timeout: 6000 })
  await page.screenshot({ path: testInfo.outputPath("actor-rail-desktop.png"), fullPage: true })
  await expect(page.getByRole("button", { name: "Reset replay" })).toHaveCount(0)
  await expect(page.getByRole("slider", { name: "Replay timeline" })).toHaveCount(0)
  const actorName = card.getByRole("button", { name: /^View / })
  expect(await actorName.evaluate(element => getComputedStyle(element).borderWidth)).toBe("0px")
  const actorLabel = await actorName.innerText()
  await actorName.click()
  await expect(page.getByRole("dialog", { name: actorLabel, exact: true })).toBeVisible()
  await page.keyboard.press("Escape")
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.getByRole("button", { name: "Report", exact: true }).click()
  await page.getByRole("tab", { name: "Actors + Stage" }).click()
  await expect(page.getByRole("slider", { name: "Replay timeline" }).first()).toBeVisible()
  expect(errors).toEqual([])
})

test("pauses following when scrolled up and resumes only at the bottom", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.addInitScript(() => localStorage.setItem("simula.language", "en"))
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  await page.request.put("/api/settings", { data: { settings } })
  const continuations: import("@playwright/test").Route[] = []
  await page.route("**/api/runs/*/continue", route => { continuations.push(route) })
  await page.goto("/")
  const chooser = page.waitForEvent("filechooser")
  await page.getByRole("button", { name: /Upload My Scenario/ }).click()
  await (await chooser).setFiles({ name: "scroll-history.md", mimeType: "text/markdown", buffer: Buffer.from("A product team debates a risky release.") })
  await page.getByLabel("Cast size").fill("6")
  await page.getByLabel("Max round").fill("3")
  await page.getByRole("switch", { name: "Auto continue" }).check()
  await page.getByRole("button", { name: "Start", exact: true }).click()
  const rail = page.getByRole("complementary", { name: "Actor history" })
  const viewport = rail.locator('[data-slot="scroll-area-viewport"]')
  const bottomGap = () => viewport.evaluate(element => element.scrollHeight - element.scrollTop - element.clientHeight)
  await expect.poll(() => continuations.length, { timeout: 12000 }).toBe(1)
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
  const bottom = await viewport.evaluate(element => element.scrollTop)
  expect(bottom).toBeGreaterThan(48)
  await viewport.hover()
  await page.mouse.wheel(0, -24)
  await expect.poll(bottomGap).toBeGreaterThan(1)
  const readingPosition = await viewport.evaluate(element => element.scrollTop)
  expect(bottom - readingPosition).toBeLessThan(48)
  await continuations[0].continue()
  await expect.poll(() => continuations.length, { timeout: 12000 }).toBe(2)
  await expect(rail.getByRole("heading", { name: "ROUND 2", exact: true })).toHaveCount(1)
  await expect.poll(() => viewport.evaluate(element => element.scrollTop)).toBeCloseTo(readingPosition, 0)
  await page.mouse.wheel(0, 10000)
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
  await continuations[1].continue()
  await expect(page.getByRole("dialog", { name: "Move to the Report page?" })).toBeVisible({ timeout: 20000 })
  await page.getByRole("button", { name: "Keep watching" }).click()
  await expect(rail.getByRole("heading", { name: "ROUND 3", exact: true })).toHaveCount(1)
  await expect.poll(bottomGap).toBeLessThanOrEqual(1)
})
