/**
 * Purpose: Verify selectable worlds, scoped manual approval, background progression, and responsive reopening.
 * Pattern: Browser workflow test with deterministic server generation.
 * Usage: bun run test:e2e apps/web/e2e/multiverse.e2e.ts
 * Related: src/ui/components/multiverse/multiverse-panel.tsx, src/backend/runtime/multiverse/jobs.ts
 */
import { expect, test } from "./fixtures"

test("two worlds retain independent approvals and finish in the background after reopening", async ({ page }, testInfo) => {
  const analysisScopes: string[] = []
  page.on("request", request => {
    if (request.method() === "POST" && new URL(request.url()).pathname === "/api/analysis") analysisScopes.push(request.postDataJSON().subject.kind)
  })
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  settings.roles.storyBuilder.provider = "openai"
  await page.request.put("/api/settings", { data: { settings } })
  await page.addInitScript(() => localStorage.setItem("simula.language", "en"))
  await page.goto("/")
  await page.getByRole("button", { name: /New Scenario/ }).click()
  let dialog = page.getByRole("main", { name: "New Scenario" })
  await dialog.getByLabel("Choose files").setInputFiles({ name: "investment.txt", mimeType: "text/plain", buffer: Buffer.from("The CTO and Finance must decide whether to invest 120 million won in the proposed project.") })
  await dialog.getByRole("checkbox", { name: "Multiverse", exact: true }).check()
  await dialog.getByLabel("Number of simulations", { exact: true }).fill("2")
  await dialog.getByRole("button", { name: "Run", exact: true }).click()
  await expect(page).toHaveURL("/document-analysis")
  dialog = page.getByRole("main")
  await expect(dialog.getByRole("button", { name: "Confirm scenario", exact: true })).toBeVisible({ timeout: 15_000 })
  await dialog.getByRole("button", { name: "Confirm scenario", exact: true }).click()
  await expect(page).toHaveURL("/simulations")
  await expect(page.getByRole("heading", { name: "Simulations", exact: true })).toBeVisible()
  await expect(page.getByRole("heading", { name: "Document analysis", exact: true })).toHaveCount(0)
  await expect(dialog.getByRole("checkbox", { name: "Multiverse", exact: true })).toBeChecked()
  const panel = dialog.getByTestId("multiverse-panel")
  await expect(panel.getByLabel("Number of simulations", { exact: true })).toHaveValue("2")
  await panel.getByLabel("Max round", { exact: true }).fill("2")
  await panel.getByLabel("Actions per type", { exact: true }).fill("1")
  await panel.getByRole("switch", { name: "Auto continue", exact: true }).uncheck()
  const created = page.waitForResponse(response => response.url().endsWith("/api/multiverse") && response.request().method() === "POST")
  await panel.getByRole("button", { name: "Start simulations", exact: true }).click()
  const { batch } = await (await created).json()
  const readBatch = async () => (await (await page.request.get(`/api/multiverse/${batch.id}`)).json()).batch
  await expect.poll(async () => (await readBatch()).worlds.map((world: { status: string }) => world.status)).toEqual(["waiting", "waiting"])
  await expect(panel.getByRole("button", { name: "Continue simulation", exact: true })).toBeVisible()
  const batchActions = panel.getByRole("group", { name: "All simulations", exact: true })
  await expect(batchActions.getByRole("button", { name: "Stop unfinished simulations", exact: true })).toBeVisible()
  await expect(batchActions.getByRole("button", { name: "Stop simulation", exact: true })).toHaveCount(0)
  const selectedPanel = panel.getByRole("region", { name: "Simulation 1", exact: true })
  expect((await batchActions.boundingBox())!.y).toBeLessThan((await selectedPanel.boundingBox())!.y)
  await panel.getByRole("button", { name: "Continue simulation", exact: true }).click()
  await expect.poll(async () => (await readBatch()).worlds.map((world: { status: string }) => world.status)).toEqual(["completed", "waiting"])
  await panel.getByRole("button", { name: "Open Multiverse report", exact: true }).click()
  await expect(page.getByRole("status")).toContainText("Other worlds are still running or awaiting approval")
  expect(analysisScopes).toEqual([])
  await page.getByRole("button", { name: "View simulations", exact: true }).click()
  await panel.getByRole("button", { name: "Simulation 2", exact: true }).click()
  await panel.getByRole("button", { name: "View simulation", exact: true }).click()
  await expect(page).toHaveURL("/simulation")
  await expect(page.getByRole("button", { name: "View simulations", exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  await page.reload()
  await page.getByRole("button", { name: "View simulations", exact: true }).click()
  await expect(page).toHaveURL("/simulations")
  await expect(panel.getByRole("button", { name: "Simulation 2", exact: true })).toHaveAttribute("aria-current", "true")
  await expect.poll(async () => (await readBatch()).worlds.map((world: { status: string }) => world.status)).toEqual(["completed", "waiting"])
  await panel.getByRole("button", { name: "View simulation", exact: true }).click()
  await expect(page).toHaveURL("/simulation")
  await page.goBack()
  await expect(page).toHaveURL("/simulations")
  await expect(panel.getByRole("button", { name: "Simulation 2", exact: true })).toHaveAttribute("aria-current", "true")
  await panel.getByRole("switch", { name: "Auto continue", exact: true }).check()
  await expect(panel.getByText("The server will continue this simulation after its countdown.")).toBeVisible()
  await page.getByRole("button", { name: "Home", exact: true }).click()
  await expect(page).toHaveURL("/")
  await page.reload()
  await expect.poll(async () => (await readBatch()).status, { timeout: 15_000 }).toBe("completed")
  await page.getByRole("button", { name: /New Scenario/ }).click()
  await expect(panel.getByRole("status")).toContainText("2 of 2 simulations completed")
  await page.screenshot({ path: testInfo.outputPath("multiverse-desktop.png"), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(async () => {
    const box = await dialog.boundingBox()
    return !!box && box.x >= 0 && box.x + box.width <= 390
  }).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollHeight > innerHeight)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("multiverse-mobile.png"), fullPage: true })
  await panel.getByRole("button", { name: "Open Multiverse report", exact: true }).click()
  await expect(page.getByRole("region", { name: "Analysis report", exact: true })).toBeVisible()
  expect(analysisScopes.length).toBeGreaterThan(0)
  expect(analysisScopes.every(scope => scope === "batch")).toBe(true)
  await page.getByRole("button", { name: "View simulations", exact: true }).click()
  await expect(page).toHaveURL("/simulations")
  await expect(panel.getByRole("combobox", { name: "Select a simulation" })).toContainText("Simulation 2")
})

test("example preview retains world count and controls through one shared scenario build", async ({ page }) => {
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  settings.roles.storyBuilder.provider = "openai"
  await page.request.put("/api/settings", { data: { settings } })
  await page.addInitScript(() => localStorage.setItem("simula.language", "en"))
  let builds = 0
  page.on("request", request => {
    if (new URL(request.url()).pathname === "/api/scenario-builder" && request.method() === "POST") builds++
  })
  await page.goto("/")
  await page.getByRole("button", { name: /Simulate Example Scenario/ }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Load sample", exact: true }).first().click()
  const preview = page.getByRole("main", { name: "Scenario Preview", exact: true })
  await expect(preview.getByLabel("Number of simulations", { exact: true })).toHaveCount(0)
  await preview.getByRole("checkbox", { name: "Multiverse", exact: true }).check()
  await preview.getByLabel("Number of simulations", { exact: true }).fill("4")
  await preview.getByLabel("Max round", { exact: true }).fill("2")
  await preview.getByRole("button", { name: "Start", exact: true }).click()
  await expect(page).toHaveURL("/document-analysis")
  await page.getByRole("button", { name: "Confirm scenario", exact: true }).click({ timeout: 30_000 })
  await expect(page).toHaveURL("/simulations")
  const panel = page.getByTestId("multiverse-panel")
  await expect(panel.getByLabel("Number of simulations", { exact: true })).toHaveValue("4")
  await expect(panel.getByLabel("Max round", { exact: true })).toHaveValue("2")
  expect(builds).toBe(1)
  await page.reload()
  await expect(panel.getByLabel("Number of simulations", { exact: true })).toHaveValue("4")
  await expect(panel.getByLabel("Max round", { exact: true })).toHaveValue("2")
  expect(builds).toBe(1)
})

test("Korean simulation controls stop one run before stopping the remaining batch", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  const { settings } = await (await page.request.get("/api/settings")).json()
  settings.providers.openai.apiKey = "unit-test-api-key"
  settings.roles.storyBuilder.provider = "openai"
  await page.request.put("/api/settings", { data: { settings } })
  await page.addInitScript(() => localStorage.setItem("simula.language", "ko"))
  await page.goto("/")
  await page.getByRole("button", { name: /새 시나리오/ }).click()
  await page.getByLabel("파일 선택").setInputFiles({ name: "decision.txt", mimeType: "text/plain", buffer: Buffer.from("검토팀이 출시 시점과 예산을 협의합니다.") })
  await page.getByRole("checkbox", { name: "Multiverse", exact: true }).check()
  await page.getByLabel("시뮬레이션 수", { exact: true }).fill("2")
  await page.getByRole("button", { name: "실행", exact: true }).click()
  await page.getByRole("button", { name: "시나리오 확정", exact: true }).click({ timeout: 15000 })
  await expect(page).toHaveURL("/simulations")
  await expect(page.getByRole("heading", { name: "문서 분석", exact: true })).toHaveCount(0)
  await page.getByLabel("최대 라운드", { exact: true }).fill("2")
  await page.getByRole("switch", { name: "자동 진행", exact: true }).uncheck()
  const created = page.waitForResponse(response => response.url().endsWith("/api/multiverse") && response.request().method() === "POST")
  await page.getByRole("button", { name: "시뮬레이션 시작", exact: true }).click()
  const { batch } = await (await created).json()
  const statuses = async () => (await (await page.request.get(`/api/multiverse/${batch.id}`)).json()).batch.worlds.map((world: { status: string }) => world.status)
  await expect.poll(statuses).toEqual(["waiting", "waiting"])
  const selected = page.getByRole("region", { name: "시뮬레이션 1", exact: true })
  await expect(selected.getByRole("button", { name: "시뮬레이션 보기", exact: true })).toBeVisible()
  const style = async (label: string) => selected.getByRole("button", { name: label, exact: true }).evaluate(button => ({
    fill: getComputedStyle(button).backgroundColor, weight: getComputedStyle(button).fontWeight,
  }))
  const controls = await Promise.all([style("시뮬레이션 진행"), style("시뮬레이션 보기"), style("시뮬레이션 중단")])
  expect(new Set(controls.map(control => control.fill)).size).toBe(3)
  expect(controls.every(control => control.weight === "600")).toBe(true)
  const review = page.getByRole("button", { name: "시나리오 검토", exact: true })
  expect(await review.evaluate(button => getComputedStyle(button).borderTopColor)).toBe("rgba(0, 0, 0, 0)")
  await page.screenshot({ path: testInfo.outputPath("simulation-controls-ko.png"), fullPage: true })
  await review.click()
  await expect(page).toHaveURL("/document-analysis")
  await expect(page.getByRole("heading", { name: "문서 분석", exact: true })).toBeVisible()
  await page.getByRole("button", { name: "시뮬레이션 보기", exact: true }).click()
  await expect(page).toHaveURL("/simulations")
  await selected.getByRole("button", { name: "시뮬레이션 중단", exact: true }).click()
  await expect.poll(statuses).toEqual(["canceled", "waiting"])
  await page.getByRole("button", { name: "진행 중인 시뮬레이션 모두 중단", exact: true }).click()
  await expect.poll(statuses).toEqual(["canceled", "canceled"])
})
